wafflestudio/wacruit-web

src/apis/auth.ts
=> Hotfix: check auth 엔드포인트 변경

src/apis/resume.ts
=> Hotfix: resume endpoint

src/components/solve/ProblemDescription/ProblemDescription.tsx
=> Feat: markdown hotfix

src/components/home/Apply.tsx, src/components/home/Countdown.tsx, src/components/home/NotificationModal.tsx, src/pages/Home.tsx
=> Fix: 리크루팅 연기

src/components/home/Apply.tsx, src/components/home/Countdown.tsx, src/components/home/NotificationModal.tsx, src/pages/Home.tsx
=> 아직 지원 기간이 아닙니다

src/components/home/Apply.tsx, src/pages/Dashboard.tsx
=> Fix: 인스타, 공지 링크

src/apis/resume.ts, src/pages/Dashboard.tsx
=> Feat: 지원 취소

src/components/rookie/Progress/ProgressCard.tsx
=> hofix: loading-status 반영 안 됨

src/components/home/Header/Header.tsx
- 상태: 
__PR 전__
__머지 전__
- 미친 사파리에서만 flex 레이아웃 안에서 끝글자를 강제개행당했길래 해당 부분 수정했습니다
=> Fix: safari line break

src/apis/resume.ts, src/components/home/Apply.tsx, src/pages/Dashboard.tsx
=> release: 사파리, 채점결과 ui 핫픽스

src/components/solve/CodeEditor/LanguageSelection.tsx, src/lib/zIndex.ts
=> Fix: language selection z-index

src/components/rookie/Progress/ProgressList.tsx, src/components/solve/CodeEditor/LanguageSelection.tsx, src/components/solve/CodeEditor/useCode.tsx, src/lib/zIndex.ts, src/pages/Resume.tsx, src/pages/Solve.tsx
23-08-04 14:00
코드, 포트폴리오 제출 불가능한 상태로 배포
=> release: without-submission

src/components/home/Header/Header.tsx
https://wafflestudio.slack.com/archives/C01KGJSRPRC/p1691127711555849
=> Fix: 헤더 로그아웃상태에서 공지사항 링크 픽스

src/apis/portfolio.ts
=> hotfix: portfolio post to s3

src/components/home/NotificationModal.tsx
- 상태:  머지 필요
https://wafflestudio.slack.com/archives/C01KGJSRPRC/p1691135981590839
__PR 전__
__머지 전__
공지모달 max-height 추가 및 스크롤바 디자
=> FIX : 공지모달 max-height 설정 및 스크롤바 디자인

src/components/rookie/Progress/ProgressList.tsx
=> 포트폴리오 카드 주석 처리

src/apis/portfolio.ts, src/components/home/Header/Header.tsx, src/components/home/NotificationModal.tsx, src/components/rookie/Progress/PortfolioCard.tsx, src/components/rookie/Progress/ProgressCard.tsx, src/components/rookie/Progress/ProgressList.tsx, src/components/rookie/Progress/ResumeCard.tsx
=> release : 공지모달, 헤더 등 기타 수정사항 반영

src/components/solve/CodeEditor/useLanguage.tsx
=> 제출 언어 id 변경

src/components/rookie/Progress/ProgressList.tsx
=> 제출 언어 id 변경 release

src/components/home/Countdown.tsx
=> fix: reset Countdown

src/apis/auth.ts
=> Fix: delete cookie with correct path and domain

package.json, src/components/solve/CodeEditor/useLanguage.tsx, yarn.lock
=> Add: kotlin, swift language support

src/components/rookie/Progress/PortfolioCard.tsx
=> Fix: delete 시 refetch

src/apis/portfolio.ts, src/components/rookie/Progress/PortfolioCard.tsx
=> Fix: post 시 refetch

src/components/rookie/Progress/PortfolioCard.tsx
링크 입력을 막는 PR
링크 입력을 막지 않도록 결정되었다면 그냥 close 해주세요
=> Fix: disable link input

src/components/rookie/Progress/PortfolioCard.tsx
=> fix: download

src/components/rookie/Progress/PortfolioCard.tsx
- 상태: 
__PR 전__
__머지 전__
사파리에서 'Choose Files' 보이는 거 수정
=> hotfix: file input Safari에서도 안 보이게 수정

src/apis/announcement.ts, src/apis/portfolio.ts
- 상태: 
__PR 전__
__머지 전__
trailing slash 제거했습니다. 서버와 컨벤션 통일을 위해!
=> Fix: delete trailing slash

src/components/rookie/Progress/PortfolioCard.tsx
=> Fix: submit link

src/apis/announcement.ts, src/apis/portfolio.ts, src/components/rookie/Progress/PortfolioCard.tsx
- 트레일링 슬래시 오류 해결
- 포트폴리오 링크 제출 가능
=> release: portfolio link

src/pages/Loader/ResumeLoader.ts, src/pages/Resume.tsx
- 상태: 
__PR 전__
__머지 전__
자소서 입력 시 put만 사용하게 Hotfix 했습니다
=> Hotfix: resume 제출 시 put만 사용하게 수정

src/components/home/Service.tsx
- 상태: 리뷰 필요
- 이슈: https://www.notion.so/wafflestudio/f623c79a4a264aa2a538ba3bf9b22310
__PR 전__
__머지 전__
- 첫 화면에서 출시 서비스 섹션으로 가서 좌우 버튼을 눌러봅시다.
- css grid 재밌습니다
=> Add: 서비스 캐러셀 애니메이션

src/components/solve/CodeEditor/index.tsx, src/components/solve/CodeEditor/useLanguage.tsx
언어별 버전을 보여주도록 수정 -- 언어 선택 오른쪽에 현재 선택한 언어의 버전이 나타난다. 디자인은 조악하나 정보 전달에는 부족함이 없을 것이다.
- 상태: 
__PR 전__
__머지 전__
=> Add: language version

src/components/home/Countdown.css
- 상태: 
__PR 전__
__머지 전__
배너의 숫자 사이에 얇은 줄 있는 거 제거
=> Fix: delete banner countdown line

src/pages/Dashboard.tsx
- 상태: 
__PR 전__
__머지 전__
지원 취소 시 쿼리 캐시 invalidate
=> hotfix: invalidate cahce when clear user

src/components/rookie/Progress/PortfolioCard.tsx, src/pages/Resume.tsx, src/pages/Solve.tsx
=> Fix: 모집 마감 알림

src/components/rookie/Progress/PortfolioCard.tsx, src/pages/Resume.tsx, src/pages/Solve.tsx
=> Fix: 모집 마감 알림 (#100)

src/components/home/NotificationModal.tsx, src/pages/Announcement.tsx
=> feat: announcement markdown에 a 태그 추가

src/components/home/Apply.tsx, src/components/home/CalenderInner.tsx, src/components/home/Introduce.tsx
=> 2024 리크루팅 문구 수정

src/components/home/CalenderInner.tsx
=> feat: 디자이너 문구 수정 (프로젝트 개수 제한)

src/apis/problem.ts, src/apis/utility.ts, src/components/solve/CodeEditor/useLanguage.tsx, src/components/solve/TestResultConsoleV2.tsx, src/main.tsx, src/pages/SolveV2.tsx, src/types/apiTypes.ts
자체 채점 서버(hodu)를 사용한 problem API v2 반영
Solve → SolveV2 로 변경
=> feat: problem API v2 반영

src/apis/problem.ts, src/apis/utility.ts, src/components/solve/ProblemDescription/ProblemDescription.tsx, src/pages/SolveV2.tsx
- 문제 풀이 에러 핸들링 로직 개선 (예상치 못한 응답이 올 때) 
- 리스트 폰트 스타일 개선
=> 문제 풀이 에러 핸들링 로직 개선 / 리스트 스타일 개선

src/GlobalStyles.tsx, src/main.tsx, src/shared/styles/designSystem.ts
디자인 시스템을 반영하였습니다.
전체 폰트를 62.5%로 설정하여 10px이 1rem으로 계산되도록 설정하였습니다.
또한 styled component의 ThemeProvider를 사용하여 디자인시스템을 설정하였습니다.
=> 💄 디자인 시스템 구축

src/components/solve/TestResultConsoleV2.tsx, src/pages/SolveV2.tsx
- 제출페이지에서 코드 초기화 버튼이 눌러도 초기화되지 않는 이슈 수정
- 테스트 버튼이 항상 disable되어있는 이슈 해결
- 코드 제출 시 문구 나타나도록 수정
=> 🐛 제출페이지에서 코드 초기화 및 테스트 실행되지 않는 버그 픽스 및 제출 시 문구 나타나도록 수정

src/components/solve/CodeEditor/useLanguage.tsx
초기 cpp 코드에 cpp 버전 정보를 추가하였습니다.
=> ✨ 주석에 cpp 버전 정보 추가

src/components/home/CalenderInner.tsx, src/components/home/Countdown.tsx, src/components/home/Introduce.tsx, src/components/solve/CodeEditor/useLanguage.tsx
=> ✨ 23.5기 정보 추가

.coderabbit.yaml
=> 코드래빗 YAML 추가

src/apis/review.ts, src/pages/Review.tsx, src/types/apiTypes.ts
후기 페이지 UI를 구현하고 API와 연결했습니다.
ENUM으로 되어 있는 포지션을 UI 상에는 첫 글자 대문자+나머지 소문자로 보이게 했습니다.
iOS는 예외적으로 반대입니다
=> ✨ 후기 페이지 UI 구현 및 API 연결

public/icon/Close.svg, public/icon/LinkArrow.svg, public/icon/NextArrow.svg, src/apis/project.ts, src/components/project/CategoryTabs.tsx, src/components/project/Layout.tsx, src/components/project/Pagination.tsx, src/components/project/ProjectCard.tsx, src/components/project/index.ts, src/entities/project/model/types.ts, src/entities/project/ui/ProjectStatusBadge.tsx, src/features/home/ui/Projects.tsx, src/features/project/index.ts, src/features/project/types.ts, src/features/project/utils.ts, src/pages/ProjectDetailV2.tsx, src/pages/ProjectV2.tsx, src/shared/api/types/project.ts, src/shared/styles/designSystem.ts, src/shared/ui/header/DesktopHeader.tsx
프로젝트 목록 페이지 및 프로젝트 상세 페이지를 구현했습니다.
- 프로젝트 목록 페이지 UI 구현 및 API 연결
- 프로젝트 상세 페이지 UI 구현 및 API 연결
- 개별 프로젝트 이미지 POST 및 GET 테스트 완료
=> ✨ 프로젝트 목록 페이지 및 프로젝트 상세 페이지 구현
